[package]
name = "humphrey"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", features = ["cuda", "ndarray", "train", "tui", "wgpu"] }
csv = "1.4.0"
kraken-async-rs = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.50.0"

[[bin]]
name="fetch"
path="src/fetch.rs"

[[bin]]
name="train"
path="src/train.rs"
